apiVersion: v1
data:
  base.conf: |
    upstream jupyter {
      server jupiter-spark:8888;
    }
    
    upstream hdfs {
      server hdfs-namenode:9870;
    }
    
    upstream hdfsui {
      server hdfs-hdfs-ui:80;
    }
    
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

    server {
      listen 8080;
      
      client_max_body_size 100G;
    
      location / {
        proxy_pass http://jupyter;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }
    }
    
    server {
      listen 8082;
      
      client_max_body_size 100G;
    
      location / {
        proxy_pass http://hdfs;
        proxy_set_header Host $host:8083;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
    
    server {
      listen 8081;
      
      client_max_body_size 100G;
    
      location / {
        proxy_pass http://hdfsui;
        proxy_set_header Host $host:8082;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: main-nginx
  labels:
    app: main-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-nginx
  template:
    metadata:
      labels:
        app: main-nginx
    spec:
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8082
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/base.conf
              name: nginx-configmap
              subPath: base.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: main-nginx
  type: ClusterIP
  ports:
    - name: jupyter
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: datanode
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: namenode
      protocol: TCP
      port: 8082
      targetPort: 8082