kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spar-kworker
          image: thecompiler1941/spark-2:latest
          command: ["./spark-worker.sh"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
