---
- name: Create keyrings
  file:
    path: /usr/share/keyrings
    state: directory
    mode: "0644"
- name: Set repository
  template:
    src: "kubernetes.list.j2"
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: "0644"
- name: Dowload repository key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
    dest: ./Release.key
    mode: "0644"
  changed_when: true
- name: Set repository key
  shell: set -o pipefail && cat ./Release.key | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
  args:
    executable: /bin/bash
  changed_when: true
- name: Clear tmp files
  file:
    state: absent
    path: ./Release.key
- name: Update apt
  apt:
    update_cache: true
    state: present
- name: Install
  package:
    name:
      - kubelet
      - kubeadm
    state: present
- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
