---
- name: "Check packages"
  package_facts:
    manager: "auto"

- name: Create hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"

- name: Upgrade APT
  apt:
    upgrade: "full"
    state: present
    update_cache: true

- name: Install packages
  package:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - rsync
      - gnupg
      - curl
      - wget
      - htop
      - git
      - vim
      - nano
      - net-tools
      - tmux
      - fzf
      #- exa
      - bat
      - jq
      - dnsutils
      - tcpdump
      - lvm2
    use: "apt"
    state: present

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/s/^/#/' /etc/fstab
  changed_when: false

- name: Enable port forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true

- name: Enable bridge-nf-call-iptables6
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: true

- name: Enable kernel modules
  shell: |
    modprobe overlay -v
    modprobe br_netfilter -v
    echo "overlay" >> /etc/modules
    echo "br_netfilter" >> /etc/modules
  changed_when: true
  
- name: Install fish
  include_tasks: fish.yml
  when: "'fish' not in ansible_facts.packages"

- name: Install starship
  include_tasks: starship.yml

- name: Install mcfly
  include_tasks: mcfly.yml

- name: Link batcat to cat
  file:
    dest: /usr/local/bin/bat
    src: /usr/bin/batcat
    state: link
  changed_when: true

- name: Apply Dotfiles
  include_tasks: dotfiles.yml
