apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hdfs-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
    app.kubernetes.io/component: hdfs-ui
    {{- include "hdfs-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hdfsUI.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
      app.kubernetes.io/component: hdfs-ui
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hdfs-ui.fullname" . }}-namenode
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
        app.kubernetes.io/component: hdfs-ui
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      affinity:
        podAntiAffinity:
          {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
                  app.kubernetes.io/component: hdfs-ui
                  {{- include "hdfs-ui.labels" . | nindent 18 }}
          {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 5
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
                    app.kubernetes.io/component: hdfs-ui
                    {{- include "hdfs-ui.labels" . | nindent 20 }}
          {{- end }}
      containers:
        - name: hdfs-ui
          image: "{{ .Values.images.hdfsUI.repository }}:{{ .Values.images.hdfsUI.tag }}"
          imagePullPolicy: {{ .Values.images.hdfsUI.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.hdfsUI.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /sysinfo
              port: http
          readinessProbe:
            httpGet:
              path: /sysinfo
              port: http
          resources:
            {{- toYaml .Values.hdfsUI.resources | nindent 12 }}
          env:
            - name: HDFS_URL
              value: "{{ include "hdfs.fullname" . }}:{{ .Values.nameNode.port }}"
            - name: HDFS_USER
              value: "{{ .Values.hdfsUI.hdfsUser }}"
            - name: HTTP_SERVER_PORT
              value: "{{ .Values.hdfsUI.port }}"
