apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
    app.kubernetes.io/component: hdfs-ui
    {{- include "hdfs-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hdfsUI.service.type }}
  ports:
    - port: {{ .Values.hdfsUI.service.port }}
      targetPort: {{ .Values.hdfsUI.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hdfs-ui.name" . }}
    app.kubernetes.io/component: hdfs-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
