---
- name: Add sshd_config include dir
  file: 
    path: "/etc/ssh/sshd_config.d"
    state: directory

- name: Create config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0664"
    validate: /usr/sbin/sshd -t -f %s
  notify: sshd_reload

- name: Add handler
  meta: flush_handlers

- name: Start sshd service
  service:
    name: sshd
    state: started
    enabled: true
